### ISSUE TITLE
Clarify section in FILEFORMATS.md

### ISSUE THREAD

**Issue by ijhoskins** [lehner-lab/DiMSum#10]
Hi @ajfaure 

I was reading over the file formats doc and noticed the section for IMPORTANT seemed to be cut short.
https://github.com/lehner-lab/DiMSum/commit/e0d1bca93a6987cab8b009c2335636f4d34140d9

Ian

**Comment by andrefaure** [comment]
Thanks for pointing out this typo! Fixed.
