### ISSUE TITLE
Requirements for use of DiMSum stages 4-5 with external count tables

### ISSUE THREAD

**Issue by ijhoskins** [lehner-lab/DiMSum#11]
In the Methods section of the paper I see that WT counts are used in normalization of fitness scores:

"DiMSum calculates fitness scores of each variant i in each replicate r as the natural logarithm of the ratio between output read counts Nioutput and input read counts Niinput relative to the wild-type variant wt"

Is the WT nucleotide string to be included in the variant counts file? 

For example, is line 100 of the example file the counts for the WT sequence?
https://github.com/lehner-lab/DiMSum/blob/master/examples/example_variantCounts.txt

Thanks in advance for your insight!

Ian

**Comment by andrefaure** [comment]
Hi @ijhoskins yes that's correct. The WT nucleotide sequence must be included in the variant counts file e.g. line 100 of the example file.

**Comment by ijhoskins** [comment]
Thanks for your input @andrefaure !
