### ISSUE TITLE
Clarify --maxSubstitutions argument

### ISSUE THREAD

**Issue by ijhoskins** [lehner-lab/DiMSum#13]
Hello @andrefaure 

Docs say "--maxSubstitutions Maximum number of nucleotide or amino acid substitutions for coding or non-coding sequences respectively (default:2)"

I was slightly confused with the word 'respectively' and its relation to the first phase. Could you confirm this means that (by default), in noncoding mode, sequences with more than 2 nt mismatches are discarded; and for coding mode, sequences with more than 2 amino acid changes are discarded?

**Comment by andrefaure** [comment]
Hi @ijhoskins yes that's correct.
