### ISSUE TITLE
There were problems while running 'dimsum__merge_report'

### ISSUE THREAD

**Issue by roserao** [lehner-lab/DiMSum#16]
Hi, I'm running DiMSum on my simulation count data but I encounter this error. What might be the cause of it? Thank you.

******* DiMSum STAGE 4 (STEAM): PROCESS VARIANT SEQUENCES *******

Loading variant count files:
dimsum_count.tsv
Processing...
	dimsum_count.tsv
Processing merged variants...
Done
Saving merged variant data...
Done
There were problems while running 'dimsum__merge_report'
There were problems while running 'dimsum__diagnostics_report'
Error in dimsum_stage_merge(dimsum_meta = pipeline[["3_tally"]], merge_outpath = pipeline[["3_tally"]][["project_path"]],  :
  object 'dimsum_meta_new_report' not found
Calls: dimsum -> dimsum_stage_merge
Execution halted

**Comment by MaximilianStammnitz** [comment]
@roserao just wondering what it was that solved your issue here? – looks like I am encountering the same error these days

**Comment by roserao** [comment]
If I remembered correctly it was a snakemake environment issue on my linux server:
1) Snakemake has a default R environment;
2) I created a few conda environments for specific packages, including dimsum as per GitHub instruction;
3) When I was running dimsum, even when I activated the dimsum conda environment, Snakemake pointed me to the *default* R environment, instead of the dimsum conda R environment;
4) I unloaded the default R env, and problem solved!

**Comment by MaximilianStammnitz** [comment]
Thanks @roserao, very good to know! The environment / R version is indeed what I have been suspecting to cause us the trouble, too. We are trying to upgrade DiMSum from R v4.0.0 to >= v4.3.x, and then this error is triggered. It comes along with a warning message:

```
Warning: Your system is mis-configured: '/var/db/timezone/localtime' is not a symlink
Warning: '/var/db/timezone/localtime' is not identical to any known timezone file
```

... so my feeling is that the Rmarkdown "report" generation may not be able to handle the missing time/date info.

**Comment by MaximilianStammnitz** [comment]
Okay, we have fixed the timezone issue but unfortunately the error which @roserao saw persists on our end. Conclusion: there may be a more general incompatibility with R versions >= 4.3.x.
