### ISSUE TITLE
Can't find indels fitness scores

### ISSUE THREAD

**Issue by BournSupremacy** [lehner-lab/DiMSum#17]
Hi there, this might be a really stupid question - but I'm struggling to find the fitness scores (and the rest of the associated data) for the indel variants that I requested be retained in my DiMSum run. Initially I was specifying specific sequence lengths but I then decided to just set the flag `-indels all` and was planning on filtering the results based on sequence length, but I'm not sure where to find these results. The `*_indel_variant_data_merge.tsv` file is empty (as expected) but I've checked the sequence lengths of the `fitness_singles.txt` and `fitness_doubles.txt` files and they are all the same length as the WT sequence (i.e., no insertions or deletions). I've also had a skim of the singles data and can see that the only mutations are the 20 aa plus stop codons. Where do the single indel variants get stored? Below is the command that I ran for DiMSum:

`DiMSum --projectName tbxta_dms_noerror --experimentDesignPath tbxta_ysd/tbxta_dimsum/experimentalDesign.txt --retainIntermediateFiles T --numCores 4 --sequenceType coding --mutagenesisType codon --indels all --mixedSubstitutions T --fitnessErrorModel F --fastqFileDir tbxta_ysd/demux/paired_end --synonymSequencePath tbxta_ysd/tbxta_dimsum/synonymSequences.txt --wildtypeSequence GCGTCCGAGCGGGATATTAAACTTTCGCTTGAAGACGCGGAGTTGTGGACCAAATTTAAAGAGCTCACCAATGAAATGATTGTCACCAAGACTGGGAGACGAATGTTTCCCGTGCTCAGAGCCAGTGTCACCGGTCTCGACCCTAATGCAATGTACTCGGTCCTGCTGGATTTTGTGGCGGCCGATAATAATCGGTGGAAATACGTGAACGGTGAA`

Thanks very much in advance for helping me with this (sort of silly) question!

**Comment by andrefaure** [comment]
Hi @BournSupremacy , the indel variants can only be found in the  `*_variant_data_merge.RData` R data object (this is the primary output file with all variants; the plain text files are just for convenience). When loaded into R you want the `all_variants` object which includes indels (see "indel" column). Hope this helps!

**Comment by BournSupremacy** [comment]
Ah, thank you very much for the quick reply! I've found it - and just in case anyone else is looking for the same thing, the R data object to load is actually the `*_fitness_replicates.RData` file! Thanks again :)

**Comment by andrefaure** [comment]
Yes sorry my mistake - corrected above.
