### ISSUE TITLE
Help with understanding experimental design

### ISSUE THREAD

**Issue by BournSupremacy** [lehner-lab/DiMSum#20]
Hey there,

First, just wanna say thanks for this truly iconic pipeline, it has made analysing my DMS data a total breeze.

But the reason I'm posting is I'm trying to understand exactly what is going on behind the scenes of DiMSum, as I can't really find the info anywhere obvious. So I have a mutant library where I am assaying the function of a protein over increasing temperatures. I have 5 experimental replicates (called YSD3 to YSD7). Within each replicate, I have 1 input sample and then 6 samples that were assayed at increased temperatures. These temperatures increase by a few degrees for each one (i.e., in each experiment replicate, I have one sample at each temperature of 28, 42 43, 44, 46 and 47). Each sample at each temperature was taken from the same input, so that single sample acts as input to all 6 of the different temperatures. I have been designating these 6 different temperatures as "selection replicates" in the experimental design file so far, but of course they are not truly replicates as the temperature actually increases between them. This is what my experimental design file looks like:

```
sample_name	experiment_replicate	selection_id	selection_replicate	technical_replicate	pair1	pair2
YSD3in	1	0			YSD3_gal_S4_R1_001.fastq.gz	YSD3_gal_S4_R2_001.fastq.gz
YSD328	1	1	1		YSD3_28_S5_R1_001.fastq.gz	YSD3_28_S5_R2_001.fastq.gz
YSD342	1	1	2		YSD3_42_S6_R1_001.fastq.gz	YSD3_42_S6_R2_001.fastq.gz
YSD343	1	1	3		YSD3_43_S7_R1_001.fastq.gz	YSD3_43_S7_R2_001.fastq.gz
YSD344	1	1	4		YSD3_44_S8_R1_001.fastq.gz	YSD3_44_S8_R2_001.fastq.gz
YSD346	1	1	5		YSD3_46_S9_R1_001.fastq.gz	YSD3_46_S9_R2_001.fastq.gz
YSD347	1	1	6		YSD3_47_S10_R1_001.fastq.gz	YSD3_47_S10_R2_001.fastq.gz
YSD4in	2	0			YSD4_gal_S11_R1_001.fastq.gz	YSD4_gal_S11_R2_001.fastq.gz
YSD428	2	1	1		YSD4_28_S12_R1_001.fastq.gz	YSD4_28_S12_R2_001.fastq.gz
YSD442	2	1	2		YSD4_42_S13_R1_001.fastq.gz	YSD4_42_S13_R2_001.fastq.gz
YSD443	2	1	3		YSD4_43_S14_R1_001.fastq.gz	YSD4_43_S14_R2_001.fastq.gz
YSD444	2	1	4		YSD4_44_S15_R1_001.fastq.gz	YSD4_44_S15_R2_001.fastq.gz
YSD446	2	1	5		YSD4_46_S16_R1_001.fastq.gz	YSD4_46_S16_R2_001.fastq.gz
YSD447	2	1	6		YSD4_47_S17_R1_001.fastq.gz	YSD4_47_S17_R2_001.fastq.gz
YSD5in	3	0			YSD5_gal_S19_R1_001.fastq.gz	YSD5_gal_S19_R2_001.fastq.gz
YSD528	3	1	1		YSD5_28_S20_R1_001.fastq.gz	YSD5_28_S20_R2_001.fastq.gz
YSD542	3	1	2		YSD5_42_S21_R1_001.fastq.gz	YSD5_42_S21_R2_001.fastq.gz
YSD543	3	1	3		YSD5_43_S22_R1_001.fastq.gz	YSD5_43_S22_R2_001.fastq.gz
YSD544	3	1	4		YSD5_44_S23_R1_001.fastq.gz	YSD5_44_S23_R2_001.fastq.gz
YSD546	3	1	5		YSD5_46_S24_R1_001.fastq.gz	YSD5_46_S24_R2_001.fastq.gz
YSD547	3	1	6		YSD5_47_S25_R1_001.fastq.gz	YSD5_47_S25_R2_001.fastq.gz
YSD6in	4	0			YSD6_gal_S27_R1_001.fastq.gz	YSD6_gal_S27_R2_001.fastq.gz
YSD628	4	1	1		YSD6_28_S28_R1_001.fastq.gz	YSD6_28_S28_R2_001.fastq.gz
YSD642	4	1	2		YSD6_42_S29_R1_001.fastq.gz	YSD6_42_S29_R2_001.fastq.gz
YSD643	4	1	3		YSD6_43_S30_R1_001.fastq.gz	YSD6_43_S30_R2_001.fastq.gz
YSD644	4	1	4		YSD6_44_S31_R1_001.fastq.gz	YSD6_44_S31_R2_001.fastq.gz
YSD646	4	1	5		YSD6_46_S32_R1_001.fastq.gz	YSD6_46_S32_R2_001.fastq.gz
YSD647	4	1	6		YSD6_47_S33_R1_001.fastq.gz	YSD6_47_S33_R2_001.fastq.gz
YSD7in	5	0			YSD7_gal_S35_R1_001.fastq.gz	YSD7_gal_S35_R2_001.fastq.gz
YSD728	5	1	1		YSD7_28_S36_R1_001.fastq.gz	YSD7_28_S36_R2_001.fastq.gz
YSD742	5	1	2		YSD7_42_S37_R1_001.fastq.gz	YSD7_42_S37_R2_001.fastq.gz
YSD743	5	1	3		YSD7_43_S38_R1_001.fastq.gz	YSD7_43_S38_R2_001.fastq.gz
YSD744	5	1	4		YSD7_44_S39_R1_001.fastq.gz	YSD7_44_S39_R2_001.fastq.gz
YSD746	5	1	5		YSD7_46_S40_R1_001.fastq.gz	YSD7_46_S40_R2_001.fastq.gz
YSD747	5	1	6		YSD7_47_S41_R1_001.fastq.gz	YSD7_47_S41_R2_001.fastq.gz
```

With this in mind, I have two questions:

1. How does DiMSum deal with the variant counts in "selection replicates"? Are they summed? Averaged? Is normalisation applied? I'm sorry if this information already exists somewhere, but I struggled to find it. Please also feel free to just point me to it if that's the case.

2. If this was your experiment, is this how you would designate it in the experimental design file? Or do you think there is a better way of designating and analysing this experiment with DiMSum? I am trying to identify which mutants retain functionality at higher temperatures and which do not compared to the wild type. If the counts of the variants are summed or averaged over the different temperatures, I could still see this trend in functionality overall but then I lose more detailed information, such as at exactly which temperature certain variants lose their functionality. Another option I suppose would be to run DiMSum once for each temperature (so 6 DiMSum runs in total) and compare the results of each run to see temperature-specific results. Just if you have time to consider it, I'd be super grateful to hear how you might think about it.

Thanks in advance for your time!

Best,
Jess

**Comment by andrefaure** [comment]
Hi Jess, I'm glad DiMSum has helped with your analysis!

1. DiMSum simply sums the variant counts over selection replicates. The intention was to model distinct replicate selections (i.e. independent output replicates from the same input) in the error model but this is as yet unimplemented. I have just updated the github docs to indicate this: https://github.com/lehner-lab/DiMSum/blob/master/docs/FILEFORMATS.md#experimental-design-file
2. Running DiMSum 6 times (once for each temperature) is definitely the way to go i.e. each of the experiment design files would have 5 input and 5 associated output samples. The input files would be identical in the 6 experiment design files of course. The idea is that DiMSum is run using data from DMS experiments that were performed under the same conditions (collection of replicate input and associated output samples). To investigate differences between conditions you will need to explicitly compare the results. 

Another option is to choose one of your temperatures as reference - you can then specify this as your "input" and the resulting fitness scores (log enrichment ratios) will then reflect changes with respect to this baseline.  You would need to run DiMSum 5 times (#temperatures - 1) and the original input samples would not be used at all in this situation.

Hope this helps!

**Comment by andrefaure** [comment]
Hi @BournSupremacy, please see the third section of the Methods of the [DiMSum paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02091-3#Sec9) for details about the fitness calculation. The WT fitness is calculated the same as any other variant and is therefore effectively zero (log(1)) or very close to zero due to rounding differences in inter-experiment normalisation.

**Comment by aturnerhi** [comment]
Hi, I have a similar question! 
I'm running an experiment with one input sample that is sorted into 3 bins based on fluorescence (high, medium, and low fluorescence).  Would each of these outputs be annotated in the experimental design file as a separate selection replicate? The file I'm using for my first replicate looks like this: 
sample_name     experiment_replicate    selection_id    selection_replicate     technical_replicate     pair1   pair2
In_Control        1       0               1
Out_Low          1       1       1       1
Out_Medium   1       1       2       1
Out_High         1       1       3       1

Or would I need to run a separate DimSum experiment for the low bin, the medium bin, and the high bin separately? 

Thanks!

**Comment by andrefaure** [comment]
Hi @aturnerhi, yes run a separate DiMSum experiment for the each of the 3 bins - selection replicate column is currently ignored.

**Comment by aturnerhi** [comment]
Great! Thank you!
