### ISSUE TITLE
DiMSum fails at Stage 4

### ISSUE THREAD

**Issue by kevinmyers** [lehner-lab/DiMSum#21]
We performed a deep sequencing experiment of a mutational library created with error prone PCR. We are focused on a single gene and have 50 million reads in the INPUT and selection sample. I'm attaching the output from the run. I am using version 1.3.1 and R version 4.0.5 and installing via Conda and running on a ScentOS 7 system.

Everything runs fine until Stage 4 when I get the following error:

```
******* DiMSum STAGE 4 (STEAM): PROCESS VARIANT SEQUENCES *******


Loading variant count files:
./TH02_DiMSum_output/tmp/3_tally/TH01_e1_s0_bNA_tNA.vsearch.unique
./TH02_DiMSum_output/tmp/3_tally/TH02_e1_s1_b1_tNA.vsearch.unique
Processing...
	TH01_e1_s0_bNA_tNA.vsearch.unique
	TH02_e1_s1_b1_tNA.vsearch.unique
Processing merged variants...
Error: Cannot proceed with variant processing: No substitution variants found
Execution halted
```

The sequencing files are Illumina short read sequences for the entire plasmid construct, but I am only providing the WT sequence for the gene of interest (minus the STOP codon). Any help getting this to run would be greatly appreciated!

[DiMSum_log.txt](https://github.com/lehner-lab/DiMSum/files/15044844/DiMSum_log.txt)

**Comment by andrefaure** [comment]
Hi @kevinmyers , DiMSum was developed to analyse targeted sequencing data of a gene/fragment of interest (single- or paired-end). DiMSum will not work with short read sequences for the entire plasmid construct.
