### ISSUE TITLE
Fastq qual above 41 leads to opaque errors in the reports

### ISSUE THREAD

**Issue by durr1602** [lehner-lab/DiMSum#22]
Hi there,

I've tried running the latest version of DiMSum (v1.3.1) on an Aviti sequencing dataset. Without specifying the `--vsearchMaxQual 45` argument, the workflow stops after the alignment. The report shows that most reads passed the cutadapt filters, but unintuitively end up in the "cutadapt not written" category in the next plot. The vsearch prefilter report recommends adding the `--fastq_qmax 45` argument (which does not work).

So, in summary:
- Maybe a new category could be added in the first plot in section 3 of the report, e.g. "max_Q_too_low"
- Maybe add the `--vsearchMaxQual` argument to the list of command-line arguments in the documentation

In the end, adding the correct argument (and [switching to r-cairo 1.5.15](https://github.com/lehner-lab/DiMSum/issues/18) to be able to read the plot labels) solved everything and the workflow ran perfectly all the way to the end :)

**Comment by andrefaure** [comment]
Thanks @durr1602 , `--vsearchMaxQual` has now been added to the list of command-line arguments in the documentation.
