### ISSUE TITLE
Miss-called sequence

### ISSUE THREAD

**Issue by mel9320107** [lehner-lab/DiMSum#9]
I'm running DiMSum with the flags below and wild-type sequence is called as 

MGLLLLRWQFARLRHLW instead of LGLLLLRWQFARLRHLW

I haven't noticed any problems in other jobs I've run, so I'm at a bit of a loss.

DiMSum \
--projectName=Tpo_L2_QC \
--experimentDesignPath=TpoR_levels_QC.txt \
--outputPath=TpoR_levels \
--retainIntermediateFiles=T \
--startStage=1 \
--wildtypeSequence=CTGGGCCTGCTGCTGCTGAGGTGGCAGTTTGCAAGACTGAGGCATCTGTGG \
--fastqFileDir=fastq \
--paired=F \
--mutagenesisType=codon \
--maxSubstitutions=2 \
--numCores=4 \
--fitnessMinInputCountAll=1 \
--experimentDesignPairDuplicates=T

First few lines of fitness_silent.txt

Pos WT_AA Mut nt_seq aa_seq Nham_nt Nham_aa Nmut_codons STOP STOP_readthrough mean_count fitness sigma
NA NA NA atgggcctgctgctgctgaggtggcagtttgcaagactgaggcatctgtgg MGLLLLRWQFARLRHLW 1 0 1 FALSE FALSE 17 -0.143357736045247 0.20071427837144
NA NA NA atgggcctgcttctgctgaggtggcagtttgcaagactgaggcatctgtgg MGLLLLRWQFARLRHLW 2 0 2 FALSE FALSE 1 -1.30147925395778 2.09851478161762
NA NA NA ctgggactgctgctgctgaggtggcagtttgcaagactgaggcatctgtgg MGLLLLRWQFARLRHLW 1 0 1 FALSE FALSE 25 -0.274872356214975 0.170651728595039
NA NA NA ctgggcctactgctgctgaggtggcagtttgcaagactgaggcatctgtgg MGLLLLRWQFARLRHLW 1 0 1 FALSE FALSE 24 0.493995640850833 0.147880669389096
NA NA NA ctgggcctcctgctgctgaggtggcagtttgcaagactgaggcatctgtgg MGLLLLRWQFARLRHLW 1 0 1 FALSE FALSE 19 -0.91009800482737 0.255980048411722

**Comment by andrefaure** [comment]
Hi @mel9320107 

This was a bug  in versions <1.2.9, see release notes:
https://github.com/lehner-lab/DiMSum/releases/tag/v1.2.9

Please update DiMSum to the latest version:
```
conda activate dimsum
conda install -c bioconda r-dimsum=1.2.11
```

**Comment by mel9320107** [comment]
Thanks for the quick response!  It's working as expected now.
